import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";



const jost = Jost({
  subsets: ["latin"],
});

export const metadata = {
  title: "IdeaVault: Startup Idea Sharing Platform",
  description: "Generated by Lalon Sheikh",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jost.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {children}
        
        <Footer></Footer>
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            duration: 2500,
          }}
        />
      </body>
    </html>
  );
}
